_wandb:
    value:
        cli_version: 0.23.1
        e:
            cmfzki957sivvdnj7nktc9m226qycb4p:
                codePath: Parte11/Ex1/main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "58581958656"
                        used: "43619479552"
                email: hugosachim@ua.pt
                executable: /usr/bin/python3
                git:
                    commit: 02e2bf204d521b38c836fc0d33679f0c06345efe
                    remote: https://github.com/HugoSachim/SAVI-Hugo-Sachim_108510-25-26.git
                host: hogu-laptop
                memory:
                    total: "8134246400"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.39
                program: /home/hogu/Desktop/SAVI-Hugo-Sachim_108510-25-26/Parte11/Ex1/./main.py
                python: CPython 3.12.3
                root: /home/hogu/Desktop/SAVI-Hugo-Sachim_108510-25-26/Parte11/Ex1
                startedAt: "2025-12-03T15:28:18.064061Z"
                writerId: cmfzki957sivvdnj7nktc9m226qycb4p
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
dataset_folder:
    value: /home/hogu/Desktop/SAVI-Hugo-Sachim_108510-25-26/savi_datasets/mnist
experiment_full_name:
    value: /home/hogu/Desktop/SAVI-Hugo-Sachim_108510-25-26/savi_datasets/savi_experiments/2025-12-03 15:28
experiment_path:
    value: /home/hogu/Desktop/SAVI-Hugo-Sachim_108510-25-26/savi_datasets/savi_experiments
num_epochs:
    value: 10
percentage_examples:
    value: 0.2
